# Generated by Django 5.2.5 on 2026-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0002_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ProRDV', max_length=100)),
                ('tagline', models.CharField(default='Votre hôtel de luxe au cœur de la ville', max_length=200)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('hero_title', models.CharField(default='Trouvez votre chambre idéale', max_length=200)),
                ('hero_subtitle', models.CharField(default='Réservez en quelques clics, profitez sans attendre.', max_length=300)),
                ('footer_description', models.TextField(default="Un hôtel d'exception au cœur de la ville, alliant luxe moderne et hospitalité authentique pour un séjour inoubliable.")),
                ('footer_address', models.CharField(default='12 Avenue des Hôtels, 75008 Paris, France', max_length=200)),
                ('footer_phone', models.CharField(default='+33 1 23 45 67 89', max_length=30)),
                ('footer_email', models.CharField(default='contact@prordv.fr', max_length=100)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
    ]
