# Generated by Django 5.2.5 on 2026-09-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='peak_months',
            field=models.CharField(default='7,8', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='peak_surcharge',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekend_surcharge',
            field=models.IntegerField(default=20),
        ),
    ]
