# Generated by Django 5.2.5 on 2026-09-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0004_sitesettings_peak_months_sitesettings_peak_surcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel_api.room')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
